source 'https://rubygems.org'

gem 'jekyll'
gem 'minimal-mistakes-jekyll'
gem 'kramdown-parser-gfm'
gem 'jekyll-feed'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-include-cache'
gem 'webrick'
